# Generated by Django 4.0.6 on 2024-08-06 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Тема сообщения')),
                ('date_sent', models.DateTimeField(verbose_name='Дата отправки')),
                ('date_received', models.DateTimeField(verbose_name='Дата получения')),
                ('message_text', models.TextField(verbose_name='Описание или текст сообщения')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/', verbose_name='Файл')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='main.message')),
            ],
        ),
    ]
