# Generated by Django 4.0.6 on 2024-08-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='source',
            field=models.CharField(default='unknown', max_length=50, verbose_name='Источник почты'),
        ),
    ]
